name: care_crafter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.1.0
  cupertino_icons: ^1.0.6
  flutter_pdfview: ^1.3.2
  image_picker: ^0.8.4+2
  path_provider: ^2.1.3
  syncfusion_flutter_pdfviewer: ^25.1.39
  kommunicate_flutter: ^1.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/referti.json
    - assets/PetVaccini.json
    - assets/vaccini.json
    - assets/data.json
    - assets/sedi.json
    - assets/oraridisponibili.json
    - assets/dottori.json
    - assets/tipovisite.json
    - assets/Vaccino.pdf
    - assets/Immagini_CareCrafter/LogoBlu.png
    - assets/Immagini_CareCrafter/logoCareCrafterR.png
    - assets/Immagini_CareCrafter/FascicoloElettronico.png
    - assets/Immagini_CareCrafter/ChattaConSpecialista.png
    - assets/Immagini_CareCrafter/Veterinario.png
    - assets/Immagini_CareCrafter/Calendar.png
    - assets/Immagini_CareCrafter/fattoria.png
    - assets/Immagini_CareCrafter/Fuffy.png
    - assets/Immagini_CareCrafter/utente.png
    - assets/Immagini_CareCrafter/Mowgly.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
